project:
  type: website
  output-dir: docs

website:
  title: "Fresh Slate Lab"
  draft-mode: unlinked
  navbar:
    left:
      - text: "Projects"
        icon: file-earmark-binary-fill
        href: projects.qmd
      - text: "Math & Stats"
        icon: calculator-fill
        href: math&stat.qmd
      - text: "Data blog"
        icon: pie-chart-fill
        href: data-blog.qmd
    right:
      - text: "Wire"
        icon: newsletter
        href: wire.qmd
      - icon: github
        href: https://github.com/ashwinbijur/
format:
  html:
    theme:
      - cosmo
      - bootswatch
    css: styles.css



