project:
  type: website
  output-dir: docs

website:
  title: "blog to follow my learnings"
  draft-mode: unlinked
  navbar:
    left:
      - text: "Data blog"
        icon: pie-chart-fill
        href: data-blog.qmd
    right:
      - text: "Coffee blog"
        icon: cup-hot-fill
        href: coffee-blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



